name: kics-scan-action

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  kics-job:
    runs-on: ubuntu-latest
    name: kics-action
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    # Scan Iac with kics
    - name: run kics Scan
      uses: checkmarx/kics-action@v1.3
      with:
        # scanning all directories
        path: '.'
        output_path: results
        output_formats: "json,html"
        verbose: true
    # Display the results in json format
    - name: Display kics results
      if: always()
      run: |
        cat results/results.json
    # Upload results after scan
    - name: Upload kics results.json
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: results-json-${{ github.run_id }}
        path: results/results.json
    - name: Upload kics results.html
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: results-html-${{ github.run_id }}
        path: results/results.html
